// apps/solid-party/src/components/3-component-composition/3-slot-fallback/card.tsx
import type { Component, JSX } from "solid-js"

type Props = {
  title?: JSX.Element
  children?: JSX.Element
}

export const Card: Component<Props> = (props) => {
  return (
    <article>
      <header>{props.title ?? <h2>Card Title</h2>}</header>
      <section>{props.children ?? <p>Card Body</p>}</section>
    </article>
  )
}

// apps/react-party/src/components/3-component-composition/3-slot-fallback/card.tsx
import type * as React from "react"
import type { FC } from "react"

type Props = {
  title?: React.ReactNode
  children?: React.ReactNode
}

export const Card: FC<Props> = ({ title, children }) => {
  return (
    <article>
      <header>{title ?? <h2>Card Title</h2>}</header>
      <section>{children ?? <p>Card Body</p>}</section>
    </article>
  )
}
