// apps/qwik-party/src/components/1-templating/4-dom-ref/focus-input.tsx
import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik"

export const FocusInput = component$(() => {
  const inputElement = useSignal<HTMLInputElement>()

  useVisibleTask$(({ track }) => {
    const el = track(inputElement)
    el?.focus()
  })

  return <input type="text" ref={inputElement} placeholder={"DomRef"} />
})

// apps/lit-party/src/components/1-templating/4-dom-ref/focus-input.ts
import { LitElement, html } from "lit"
import { customElement, query } from "lit/decorators.js"

@customElement("focus-input")
export class FocusInput extends LitElement {
  @query("input")
  private inputElement!: HTMLInputElement

  firstUpdated() {
    this.inputElement.focus()
  }

  render() {
    return html`
      <div>
        <input type="text" placeholder="This input will be focused">
      </div>
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "focus-input": FocusInput
  }
}
