// apps/qwik-party/src/components/3-component-composition/1-emit-to-parent/count-action.tsx
import { type PropFunction, component$ } from "@builder.io/qwik"

type Props = {
  onIncrease$: PropFunction<() => void>
  onDecrease$: PropFunction<() => void>
}

export const CountAction = component$((props: Props) => {
  return (
    <>
      <button type={"button"} onClick$={props.onIncrease$}>
        Increase
      </button>
      <button type={"button"} onClick$={props.onDecrease$}>
        Decrease
      </button>
    </>
  )
})

// apps/react-party/src/components/3-component-composition/1-emit-to-parent/count-action.tsx
type Props = {
  onIncrease: () => void
  onDecrease: () => void
}

export const CountAction = (props: Props) => {
  return (
    <>
      <button type={"button"} onClick={props.onIncrease}>
        Increase
      </button>
      <button type={"button"} onClick={props.onDecrease}>
        Decrease
      </button>
    </>
  )
}
