// apps/solid-party/src/components/1-templating/5-conditional/level-display.tsx
import { createSignal } from "solid-js"

export const LevelDisplay = () => {
  const [count, setCount] = createSignal(0)

  const increase = () => {
    setCount(count() + 1)
  }

  const decrease = () => {
    setCount(count() - 1)
  }

  return (
    <div style={{ display: "flex", "flex-direction": "column", gap: "1rem" }}>
      <button type="button" onClick={increase}>
        Increase
      </button>
      <div>
        Counter {count()}
        {count() < 3 && <div>Low Level</div>}
        {count() >= 3 && count() <= 6 && <div>Middle Level</div>}
        {count() > 6 && <div>High Level</div>}
      </div>
      <button type="button" onClick={decrease}>
        Decrease
      </button>
    </div>
  )
}

// apps/vue-party/src/components/1-templating/5-conditional/LevelDisplay.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const increase = () => {
  count.value++
}

const decrease = () => {
  count.value--
}
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 1rem;">
    <button type="button" @click="increase">
      Increase
    </button>
    <div>
      Counter {{ count }}
      <div v-if="count < 3">Low Level</div>
      <div v-else-if="count >= 3 && count <= 6">Middle Level</div>
      <div v-else>High Level</div>
    </div>
    <button type="button" @click="decrease">
      Decrease
    </button>
  </div>
</template>
