// apps/react-party/src/components/3-component-composition/0-props/count-content.tsx
import { useState } from "react"
import { CountDisplay } from "./count-display.tsx"

export const CountContent = () => {
  const [count, setCount] = useState(0)

  return (
    <div>
      <button type={"button"} onClick={() => setCount((count) => count + 1)}>
        Increment
      </button>
      <CountDisplay count={count} />
    </div>
  )
}

// apps/solid-party/src/components/3-component-composition/1-emit-to-parent/count-content.tsx
import { createSignal } from "solid-js"
import { CountDisplay } from "./count-display.tsx"

export const CountContent = () => {
  const [count, setCount] = createSignal(0)

  return (
    <div>
      <CountDisplay count={count()} setCount={setCount} />
      <div>Parent Count: {count()}</div>
    </div>
  )
}
