// apps/qwik-party/src/components/3-component-composition/3-slot-fallback/app.tsx
import { Card } from "./card.tsx"

export const App = () => {
  return (
    <div>
      <Card>
        <span q:slot="title">Qwik</span>
        <span q:slot="body">Content</span>
      </Card>
      <Card>
        <span q:slot="title">No content</span>
      </Card>
      <Card>
        <span q:slot="body">No header</span>
      </Card>
    </div>
  )
}

// apps/vue-party/src/components/3-component-composition/3-slot-fallback/App.vue
<script setup lang="ts">
import Card from './Card.vue'
</script>

<template>
  <div>
    <Card>
      <template #title>Custom Title</template>
      <template #body>Custom Body</template>
    </Card>

    <Card>
      <template #title>Only Title</template>
    </Card>

    <Card>
      <template #body>Only Body</template>
    </Card>

    <Card />
  </div>
</template>
