// apps/qwik-party/src/components/3-component-composition/3-slot-fallback/card.tsx
import { Slot, component$, useStylesScoped$ } from "@builder.io/qwik"

export const Card = component$(() => {
  useStylesScoped$(`
    .card {
      border: 1px solid #ccc;
      border-radius: 4px;
      padding: 16px;
      margin: 16px 0;
    }
    .title {
      font-size: 1.2em;
      font-weight: bold;
      margin-bottom: 8px;
    }
    .title:empty::before {
      content: 'Fallback title'
    }
    .body {
      font-size: 1em;
    }
    
    .body:empty::before {
      content: 'Fallback body'
    }
  `)
  return (
    <article class="card">
      <header class="title">
        <Slot name="title" />
      </header>
      <section class="body">
        <Slot name="body" />
      </section>
    </article>
  )
})

// apps/vue-party/src/components/3-component-composition/3-slot-fallback/Card.vue
<template>
  <article class="card">
    <header class="title">
      <slot name="title">
        Fallback title
      </slot>
    </header>
    <section class="body">
      <slot name="body">
        Fallback body
      </slot>
    </section>
  </article>
</template>

<style scoped>
.card {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 16px;
  margin: 16px 0;
}
.title {
  font-size: 1.2em;
  font-weight: bold;
  margin-bottom: 8px;
}
.body {
  font-size: 1em;
}
</style>
