// apps/vue-party/src/components/3-component-composition/3-slot-fallback/App.vue
<script setup lang="ts">
import Card from './Card.vue'
</script>

<template>
  <div>
    <Card>
      <template #title>Custom Title</template>
      <template #body>Custom Body</template>
    </Card>

    <Card>
      <template #title>Only Title</template>
    </Card>

    <Card>
      <template #body>Only Body</template>
    </Card>

    <Card />
  </div>
</template>

// apps/solid-party/src/components/3-component-composition/3-slot-fallback/app.tsx
import { Card } from "./card"

export const App = () => {
  return (
    <div>
      <Card>
        <div slot="title">Custom Title</div>
        <div slot="body">Custom Body</div>
      </Card>
      <Card>
        <div slot="title">Only Title</div>
      </Card>
      <Card>
        <div slot="body">Only Body</div>
      </Card>
      <Card />
    </div>
  )
}
