// apps/react-party/src/components/3-component-composition/1-emit-to-parent/count-content.tsx
import { useState } from "react"
import { CountAction } from "./count-action.tsx"

export const CountContent = () => {
  const [count, setCount] = useState(0)
  const onIncrease = () => {
    setCount((count) => count + 1)
  }
  const onDecrease = () => {
    setCount((count) => count - 1)
  }

  return (
    <div>
      <div>Count {count}</div>
      <CountAction onIncrease={onIncrease} onDecrease={onDecrease} />
    </div>
  )
}

// apps/qwik-party/src/components/3-component-composition/1-emit-to-parent/count-content.tsx
import { $, component$, useSignal } from "@builder.io/qwik"
import { CountAction } from "./count-action.tsx"

export const CountContent = component$(() => {
  const count = useSignal(0)
  const onIncrease = $(() => {
    count.value = count.value + 1
  })
  const onDecrease = $(() => {
    count.value = count.value - 1
  })

  return (
    <div>
      <div>Count {count.value}</div>
      <CountAction onIncrease$={onIncrease} onDecrease$={onDecrease} />
    </div>
  )
})
