// apps/react-party/src/components/2-lifecycle/1-on-unmount/time.tsx
import { useEffect, useState } from "react"

export const Time = () => {
  const [time, setTime] = useState(new Date().toLocaleTimeString())

  useEffect(() => {
    const timer = setInterval(() => {
      setTime(new Date().toLocaleTimeString())
    }, 1000)

    return () => clearInterval(timer)
  }, [])

  return <p>Current time: {time}</p>
}

// apps/solid-party/src/components/2-lifecycle/1-on-unmount/time.tsx
import { createSignal, onCleanup } from "solid-js"

export const Time = () => {
  const [time, setTime] = createSignal(new Date().toLocaleTimeString())

  const timer = setInterval(() => {
    setTime(new Date().toLocaleTimeString())
  }, 1000)

  onCleanup(() => {
    clearInterval(timer)
  })

  return <div>Current Time: {time()}</div>
}
