// apps/vue-party/src/components/4-form-input/1-checkbox/Checkbox.vue
<script setup lang="ts">
import { ref } from "vue"

const isChecked = ref(false)
</script>

<template>
  <div>
    <label>
      <input
        type="checkbox"
        v-model="isChecked"
      />
      Check me
    </label>
    <p>Checkbox is {{ isChecked ? 'checked' : 'unchecked' }}</p>
  </div>
</template>

// apps/lit-party/src/components/4-form-input/1-checkbox/checkbox.ts
import { LitElement, html } from "lit"
import { customElement, state } from "lit/decorators.js"

@customElement("checkbox-input")
export class CheckboxInput extends LitElement {
  @state()
  private isChecked = false

  private handleChange(e: Event) {
    this.isChecked = (e.target as HTMLInputElement).checked
  }

  render() {
    return html`
      <div>
        <label>
          <input 
            type="checkbox"  
            .checked=${this.isChecked} 
            @change=${this.handleChange}
          />
          Check me
        </label>
        <p>Checkbox is ${this.isChecked ? "checked" : "unchecked"}</p>
      </div>
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "checkbox-input": CheckboxInput
  }
}
