// apps/qwik-party/src/components/4-form-input/1-checkbox/checkbox.tsx
import { component$, useSignal } from "@builder.io/qwik"

export const Checkbox = component$(() => {
  const isAvailable = useSignal(false)

  return (
    <div>
      <input id="is-available" type="checkbox" bind:checked={isAvailable} />
      <label for="is-available">Is available</label>
    </div>
  )
})

// apps/react-party/src/components/4-form-input/1-checkbox/checkbox.tsx
import type React from "react"
import { useState } from "react"

export const Checkbox: React.FC = () => {
  const [isAvailable, setIsAvailable] = useState(false)

  return (
    <div>
      <input id="is-available" type="checkbox" checked={isAvailable} onChange={(e) => setIsAvailable(e.target.checked)} />
      <label htmlFor="is-available">Is available</label>
    </div>
  )
}
