// apps/solid-party/src/components/0-reactivity/2-computed-state/double-count.tsx
import { createMemo, createSignal } from "solid-js"

export const DoubleCount = () => {
  const [count] = createSignal(10)
  const doubleCount = () => count() * 2
  const doubleCountMemo = createMemo(() => count() * 2)

  return (
    <div>
      <div>Count: {count()}</div>
      <div>Double Count: {doubleCount()}</div>
      <div>Double Count Memo: {doubleCountMemo()}</div>
    </div>
  )
}

// apps/react-party/src/components/0-reactivity/2-computed-state/double-count.tsx
import { useMemo, useState } from "react"

export const DoubleCount = () => {
  const [count] = useState(10)
  const doubleCount = count * 2
  const doubleCountMemo = useMemo(() => count * 2, [count])
  return (
    <div>
      <div>Count: {count}</div>
      <div>Double Count: {doubleCount}</div>
      <div>Double Count Memo: {doubleCountMemo}</div>
    </div>
  )
}
