// apps/react-party/src/components/4-form-input/1-checkbox/checkbox.tsx
import type React from "react"
import { useState } from "react"

export const Checkbox: React.FC = () => {
  const [isAvailable, setIsAvailable] = useState(false)

  return (
    <div>
      <input id="is-available" type="checkbox" checked={isAvailable} onChange={(e) => setIsAvailable(e.target.checked)} />
      <label htmlFor="is-available">Is available</label>
    </div>
  )
}

// apps/solid-party/src/components/4-form-input/1-checkbox/checkbox.tsx
import { createSignal } from "solid-js"

export const Checkbox = () => {
  const [checked, setChecked] = createSignal(false)

  return (
    <>
      <p>Checked: {checked().toString()}</p>
      <input
        type="checkbox"
        checked={checked()}
        onChange={(e) => setChecked(e.currentTarget.checked)}
      />
    </>
  )
}
