// apps/react-party/src/components/1-templating/3-event-click/count-increment.tsx
import { useState } from "react"

export const CountIncrement = () => {
  const [count, setCount] = useState(0)

  const incrementCount = () => {
    setCount((count) => count + 1)
  }

  return (
    <div>
      <p>Counter: {count}</p>
      <button type={"button"} onClick={incrementCount}>
        Increment
      </button>
    </div>
  )
}

// apps/qwik-party/src/components/1-templating/3-event-click/count-increment.tsx
import { $, component$, useSignal } from "@builder.io/qwik"

export const CountIncrement = component$(() => {
  const count = useSignal(0)

  const incrementCount = $(() => {
    count.value++
  })

  return (
    <div>
      <p>Counter: {count.value}</p>
      <button type={"button"} onClick$={incrementCount}>
        Increment
      </button>
    </div>
  )
})
