// apps/qwik-party/src/components/3-component-composition/0-props/count-content.tsx
import { component$, useSignal } from "@builder.io/qwik"
import { CountDisplay } from "./count-display.tsx"

export const CountContent = component$(() => {
  const count = useSignal(0)

  return (
    <div>
      <button type={"button"} onClick$={() => count.value++}>
        Increment
      </button>
      <CountDisplay count={count.value} />
    </div>
  )
})

// apps/react-party/src/components/3-component-composition/0-props/count-content.tsx
import { useState } from "react"
import { CountDisplay } from "./count-display.tsx"

export const CountContent = () => {
  const [count, setCount] = useState(0)

  return (
    <div>
      <button type={"button"} onClick={() => setCount((count) => count + 1)}>
        Increment
      </button>
      <CountDisplay count={count} />
    </div>
  )
}
