// apps/qwik-party/src/components/3-component-composition/4-context/theme-toggle.tsx
import { component$, useContext } from "@builder.io/qwik"
import { ThemeContext } from "./theme-context.ts"

export const ThemeToggle = component$(() => {
  const theme = useContext(ThemeContext)
  return (
    <div>
      <button
        type={"button"}
        onClick$={() => {
          theme.value = theme.value === "dark" ? "light" : "dark"
        }}
      >
        Flip
      </button>
    </div>
  )
})

// apps/react-party/src/components/3-component-composition/4-context/theme-toggle.tsx
import { useContext } from "react"
import { ThemeContext } from "./theme-context.tsx"

export const ThemeToggle = () => {
  const { theme, toggleTheme } = useContext(ThemeContext)

  return (
    <div>
      <p>Current theme: {theme}</p>
      <button type={"button"} onClick={toggleTheme}>
        Toggle Theme
      </button>
    </div>
  )
}
