// apps/react-party/src/components/2-lifecycle/1-on-unmount/time.tsx
import { useEffect, useState } from "react"

export const Time = () => {
  const [time, setTime] = useState(new Date().toLocaleTimeString())

  useEffect(() => {
    const timer = setInterval(() => {
      setTime(new Date().toLocaleTimeString())
    }, 1000)

    return () => clearInterval(timer)
  }, [])

  return <p>Current time: {time}</p>
}

// apps/vue-party/src/components/2-lifecycle/1-on-unmount/Time.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const time = ref(new Date().toLocaleTimeString())

let timer: number

onMounted(() => {
  timer = setInterval(() => {
    time.value = new Date().toLocaleTimeString()
  }, 1000)
})

onUnmounted(() => {
  clearInterval(timer)
})
</script>

<template>
  <p>Current time: {{ time }}</p>
</template>
