// apps/solid-party/src/components/1-templating/3-event-click/count-increment.tsx
import { createSignal } from "solid-js"

export const CountIncrement = () => {
  const [count, setCount] = createSignal(0)

  const increment = () => setCount(count() + 1)

  return (
    <div>
      <div>Count: {count()}</div>
      <button type={"button"} onClick={increment}>
        Increment
      </button>
    </div>
  )
}

// apps/react-party/src/components/1-templating/3-event-click/count-increment.tsx
import { useState } from "react"

export const CountIncrement = () => {
  const [count, setCount] = useState(0)

  const incrementCount = () => {
    setCount((count) => count + 1)
  }

  return (
    <div>
      <p>Counter: {count}</p>
      <button type={"button"} onClick={incrementCount}>
        Increment
      </button>
    </div>
  )
}
