// apps/vue-party/src/components/5-webapp-features/1-fetch-data/App.vue
<script setup lang="ts">
import useFetchUsers from "./useFetchUser"

const { isLoading, error, data: users } = useFetchUsers()
</script>

<template>
  <p v-if="isLoading">Fetching users...</p>
  <p v-else-if="error">An error while fetching users</p>
  <ul v-else-if="users">
    <li
        v-for="user in users"
        :key="user.login.uuid"
    >
      <img
          :src="user.picture.thumbnail"
          alt="user"
      >
      <p>
        {{ user.name.first }}
        {{ user.name.last }}
      </p>
    </li>
  </ul>
</template>

<style scoped>

</style>

// apps/svelte-party/src/components/5-webapp-features/1-fetch-data/App.svelte
<script>
import { useFetchUsers } from "./useFetchsers.svelte.js"

const response = useFetchUsers()
</script>

{#if response.isLoading}
  <p>Fetching users...</p>
{:else if response.error}
  <p>An error occurred while fetching users</p>
{:else if response.users}
  <ul>
    {#each response.users as user}
      <li>
        <img src={user.picture.thumbnail} alt="user" />
        <p>
          {user.name.first}
          {user.name.last}
        </p>
      </li>
    {/each}
  </ul>
{/if}
