// apps/qwik-party/src/components/5-webapp-features/1-fetch-data/app.tsx
import { Resource, component$, useResource$, useStylesScoped$ } from "@builder.io/qwik"

type UsersResponse = {
  results: {
    picture: {
      thumbnail: string
    }
    name: {
      first: string
      last: string
    }
  }[]
}

export const fetchUsers = async () => {
  return (await fetch("https://randomuser.me/api/?results=3")).json()
}

export const App = component$(() => {
  const data = useResource$<UsersResponse>(fetchUsers)

  useStylesScoped$(`
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
      padding: 10px;
      border-radius: 5px;
    }
    img {
      border-radius: 50%;
      margin-right: 15px;
    }
    p {
      margin: 0;
      font-size: 18px;
    }
  `)

  return (
    <Resource
      value={data}
      onPending={() => <p>Fetching users...</p>}
      onRejected={() => <p>An error occurred while fetching users</p>}
      onResolved={({ results: users }) => (
        <ul>
          {users.map((user, index) => (
            <li key={index}>
              <img src={user.picture.thumbnail} alt={`${user.name.first} ${user.name.last}`} />
              <p>
                {user.name.first} {user.name.last}
              </p>
            </li>
          ))}
        </ul>
      )}
    />
  )
})

// apps/react-party/src/components/5-webapp-features/1-fetch-data/app.tsx
import type React from "react"
import { useEffect, useState } from "react"

type UsersResponse = {
  results: {
    picture: {
      thumbnail: string
    }
    name: {
      first: string
      last: string
    }
  }[]
}

export const fetchUsers = async (): Promise<UsersResponse> => {
  const response = await fetch("https://randomuser.me/api/?results=3")
  return response.json()
}

export const App: React.FC = () => {
  const [users, setUsers] = useState<UsersResponse["results"] | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchUsers()
      .then((data) => {
        setUsers(data.results)
        setIsLoading(false)
      })
      .catch(() => {
        setError("An error occurred while fetching users")
        setIsLoading(false)
      })
  }, [])

  if (isLoading) return <p>Fetching users...</p>
  if (error) return <p>{error}</p>

  return (
    <ul>
      {users?.map((user) => (
        <li key={`user-${user.name.first}-${user.name.last}`}>
          <img src={user.picture.thumbnail} alt={`${user.name.first} ${user.name.last}`} />
          <p>
            {user.name.first} {user.name.last}
          </p>
        </li>
      ))}
    </ul>
  )
}
