// apps/react-party/src/components/3-component-composition/4-context/theme-toggle.tsx
import { useContext } from "react"
import { ThemeContext } from "./theme-context.tsx"

export const ThemeToggle = () => {
  const { theme, toggleTheme } = useContext(ThemeContext)

  return (
    <div>
      <p>Current theme: {theme}</p>
      <button type={"button"} onClick={toggleTheme}>
        Toggle Theme
      </button>
    </div>
  )
}

// apps/lit-party/src/components/3-component-composition/4-context/theme-toggle.ts
import { consume } from "@lit/context"
import { LitElement, html } from "lit"
import { customElement, property } from "lit/decorators.js"
import { themeContext } from "./theme-context.ts"

@customElement("theme-toggle")
export class ThemeToggle extends LitElement {
  @consume({ context: themeContext })
  @property({ type: Object, attribute: false })
  theme

  @property({ type: Function, attribute: false })
  updateTheme

  render() {
    return html`
      <div>
        <button @click="${this.updateTheme}">
          Toggle Theme
        </button>
      </div>
    `
  }
}
