// apps/react-party/src/components/4-form-input/2-radio/radio.tsx
import type React from "react"
import { useState } from "react"

export const Radio: React.FC = () => {
  const [pickedColor, setPickedColor] = useState("red")

  return (
    <>
      <div>Picked: {pickedColor}</div>
      <input id="blue-pill" type="radio" checked={pickedColor === "blue"} onChange={() => setPickedColor("blue")} value="blue" />
      <label htmlFor="blue-pill">Blue</label>

      <input id="red-pill" type="radio" checked={pickedColor === "red"} onChange={() => setPickedColor("red")} value="red" />
      <label htmlFor="red-pill">Red</label>
    </>
  )
}

// apps/qwik-party/src/components/4-form-input/2-radio/radio.tsx
import { component$, useSignal } from "@builder.io/qwik"

export const Radio = component$(() => {
  const pickedColor = useSignal("red")

  return (
    <>
      <div>Picked: {pickedColor.value}</div>
      <input id="blue-pill" type="radio" bind:value={pickedColor} checked={pickedColor.value === "blue"} value="blue" />
      <label for="blue-pill">Blue</label>

      <input id="red-pill" type="radio" checked={pickedColor.value === "red"} bind:value={pickedColor} value="red" />
      <label for="red-pill">Red</label>
    </>
  )
})
