// apps/qwik-party/src/components/2-lifecycle/1-on-unmount/time.tsx
import { component$, useStore, useVisibleTask$ } from "@builder.io/qwik"

export const Time = component$(() => {
  const store = useStore({
    time: new Date().toLocaleTimeString()
  })

  useVisibleTask$(({ cleanup }) => {
    const timer = setInterval(() => {
      store.time = new Date().toLocaleTimeString()
    }, 1000)

    cleanup(() => clearInterval(timer))
  })

  return <p>Current time: {store.time}</p>
})

// apps/react-party/src/components/2-lifecycle/1-on-unmount/time.tsx
import { useEffect, useState } from "react"

export const Time = () => {
  const [time, setTime] = useState(new Date().toLocaleTimeString())

  useEffect(() => {
    const timer = setInterval(() => {
      setTime(new Date().toLocaleTimeString())
    }, 1000)

    return () => clearInterval(timer)
  }, [])

  return <p>Current time: {time}</p>
}
