// apps/vue-party/src/components/1-templating/5-conditional/LevelDisplay.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const increase = () => {
  count.value++
}

const decrease = () => {
  count.value--
}
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 1rem;">
    <button type="button" @click="increase">
      Increase
    </button>
    <div>
      Counter {{ count }}
      <div v-if="count < 3">Low Level</div>
      <div v-else-if="count >= 3 && count <= 6">Middle Level</div>
      <div v-else>High Level</div>
    </div>
    <button type="button" @click="decrease">
      Decrease
    </button>
  </div>
</template>

// apps/svelte-party/src/components/1-templating/5-conditional/LevelDisplay.svelte
<script lang="ts">
import { writable } from "svelte/store"

const count = writable(0)

const increase = () => {
  count.update((n) => n + 1)
}

const decrease = () => {
  count.update((n) => n - 1)
}
</script>

<div style="display: flex; flex-direction: column; gap: 1rem;">
  <button type="button" onclick={increase}>
    Increase
  </button>
  <div>
    Counter {$count}
    {#if $count < 3}
      <div>Low Level</div>
    {:else if $count >= 3 && $count <= 6}
      <div>Middle Level</div>
    {:else if $count > 6}
      <div>High Level</div>
    {/if}
  </div>
  <button type="button" onclick={decrease}>
    Decrease
  </button>
</div>
